default: &default
  adapter: postgresql
  database: showup_production
  # user: postgres
  # password: 
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: development.sqlite3
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: test.sqlite3
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
