default: &default
  adapter: postgresql
  database: showup
  user: postgres
  password: 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: showup

test:
  <<: *default
  database: showup
