default: &default
  adapter: postgresql
  database: showup_production
  # user: postgres
  # password: 
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: showup_development
  username: postgres
  password: 
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: showup
